# NOTE: taken from https://github.com/MylesBorins/node-osc/blob/main/.github/workflows/bump-version.yml

name: Bump version & Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver type of new version'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
          - prerelease
      prereleaseid:
        description: 'Prerelease id (rc)'
        required: false
        default: ''

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
    - name: Check out source
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install npm packages
      run: npm ci

    - name: Setup Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

      ## am I crazy or is this 'run' crazy?
    - name: bump version
      run: |
        npm version ${{ github.event.inputs.version }} -w configs/base --no-git-tag-version --preid ${{ github.event.inputs.prereleaseid }}
        git add .
        git commit -m "configs-base v$(npm pkg get version --prefix configs/base | tr -d '"')"
        git tag @muban/eslint-config@$(npm pkg get version --prefix configs/base | tr -d '"') -m "configs-base v$(npm pkg get version --prefix configs/base | tr -d '"')"

    - name: publish
      run: |
        npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        npm publish -w configs/base
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Push latest version
      run: git push origin main --follow-tags
