# NOTE: taken from https://github.com/MylesBorins/node-osc/blob/main/.github/workflows/bump-version.yml

name: Tag & Publish

on:
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out source
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install npm packages
      run: npm ci

    - name: Setup Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Create tag
      run: |
        git tag @muban/eslint-config@$(npm pkg get version --prefix configs/base | tr -d '"') -m "configs-base v$(npm pkg get version --prefix configs/base | tr -d '"')"

    - name: Publish
      run: |
        npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        npm publish -w configs/base
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Push tag
      run: git push origin main --follow-tags
